### ISSUE TITLE
Activate acceptance tests on Travis CI for Puppet Enterprise, at least 2.8.8 and 3.8.2

### ISSUE THREAD

**Issue by cardil** [coi-gov-pl/puppet-jboss#3]
Travis CI is unable to run acceptance tests on docker because of low disk space.

Maybe on new Travis CI infrastructure this can be executed?

* http://www.camptocamp.com/en/actualite/puppet-acceptance-tests-travis-ci-docker/ 
* http://docs.travis-ci.com/user/docker/

Failed builds:

 * PE 2.8.8: https://travis-ci.org/coi-gov-pl/puppet-jboss/jobs/75097833
 * PE 3.8.2: https://travis-ci.org/coi-gov-pl/puppet-jboss/jobs/75097834

Required fragment in `.travis.yml` file:

```yaml
 - rvm: default
   sudo: required
   services: docker
   env: RS_SET="centos-6-x86_64-pe288-docker"
   script: bundle exec rake acceptance
 - rvm: default
   sudo: required
   services: docker
   env: RS_SET="centos-6-x86_64-pe382-docker"
   script: bundle exec rake acceptance
```

@coi-gov-pl/jboss-puppet-team
