### ISSUE TITLE
Try to execute standard Ruby builds on Travis CI on container infrastructure

### ISSUE THREAD

**Issue by cardil** [coi-gov-pl/puppet-jboss#4]
Travis has enabled container infrastructure that's runs faster and can enable bundler cache. Downside for this is you are not able to run `sudo` command and therefore can't install anything as usual.

JBoss module uses a `augeas` lenses that should be newer `1.0.0` in order to rspec tests work. This is normally handled for older systems with jbxml-shim that uses newer version of XML lens. This is not possible in noop mode and unit tests. So `libaugeas-dev >= 1.0.0` needs to be installed as a system dependency.

Currently this is handled by Travis install script https://github.com/coi-gov-pl/puppet-jboss/blob/develop/.travis.yml#L7

```yaml
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install -y libaugeas-dev libxml2-dev
```

In container based infrastructure this can be done with this fragment:

```yaml
sudo: false
addons:
  apt:
    sources:
    - ppa:raphink/augeas
    packages:
    - libaugeas-dev
    - libxml2-dev
bundler_args: --without development --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
cache: bundler
```

Problem is that `ppa:raphink/augeas` is not considered trusted, and Travis installs default packages insead of newer versions: https://travis-ci.org/coi-gov-pl/puppet-jboss/jobs/81567020

Notify: @coi-gov-pl/jboss-puppet-team
